# Generated by Django 3.0.7 on 2020-08-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20200802_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='claimed',
        ),
    ]
