# Generated by Django 3.0.7 on 2020-08-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_recipe_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images'),
        ),
    ]
