# Generated by Django 3.0.7 on 2020-08-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20200803_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='recipe_images'),
        ),
    ]
