# Generated by Django 3.0.7 on 2020-08-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20200804_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='loopTime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
